In [1]:
import numpy as np

In [4]:
def convolve(x, kernel):
    x_height = x.shape[0]
    x_width = x.shape[1]
    
    kernel_height = kernel.shape[0]
    kernel_width = kernel.shape[1]
    
    H = (kernel_height - 1) // 2
    W = (kernel_width - 1) // 2
    
    out = np.zeros((x_height, x_width))
    # iterate over all the pixel of image X
    for i in np.arange(H, x_height - H):
        for j in np.arange(W, x_width - W):
            sum = 0
            # iterate over the filter
            for k in np.arange(-H, H + 1):
                for l in np.arange(-W, W + 1):
                    # get the corresponding value from image and filter
                    a = x[i + k, j + l]
                    w = kernel[H + k, W + l]
                    sum += (w * a)
            out[i, j] = sum
    return out

In [5]:
# Define the 3x3 kernel
x_kernel = np.array([[-1, 0, 1],
                     [-1, 0, 1],
                     [-1, 0, 1]])

In [44]:
x = np.random.randint(0, 256, (128, 128), dtype=np.uint8)
print("Input Matrix (5x5):")
print(x)

Input Matrix (5x5):
[[130 251  32 ... 247  21  53]
 [ 86 183 180 ...  48 100  35]
 [197 191  38 ... 130 151  65]
 ...
 [158 157 210 ...  28 162 108]
 [128 184 142 ...  59 245 108]
 [152 210  33 ... 225 188 209]]


In [43]:
output = convolve(x, x_kernel)
print("\nOutput Matrix after Convolution:")
print(output)


Output Matrix after Convolution:
[[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.  -76. -103.  332.   89. -286.   16.  -28. -210.    0.]
 [   0.  -72.   77.  158. -216. -139.  106.  -61.  -76.    0.]
 [   0.   -3. -189.  -12.  -82.   78.  -25.  -85.  -27.    0.]
 [   0. -231. -258.  -54.  -26.   -5.  -94.   23.   42.    0.]
 [   0. -119. -285. -114.  -83.   83.   19. -100.  142.    0.]
 [   0.  -29. -148. -271.   41.  123.  -87.   41.  186.    0.]
 [   0.  140.  -31. -326. -172.  353.   64.  -55.  268.    0.]
 [   0.  397. -103. -540.   46.  344.  170.  148.    7.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]]


In [50]:
import numpy as np

# Define the size of the array
ROWS = 128
COLS = 128

# Generate a ROWS x COLS array of random 8-bit integers (0-255)
array = np.random.randint(0, 256, size=(ROWS, COLS))

# Convert the array to C array format
c_array_str = f"int x[ROWS][COLS] = {{\n"
for row in array:
    c_array_str += "    {" + ", ".join(map(str, row)) + "},\n"
c_array_str = c_array_str.rstrip(",\n") + "\n};"

# Save to a text file
with open("c_array.txt", "w") as file:
    file.write(c_array_str)

print("C array saved to c_array_128x128.txt")


C array saved to c_array_128x128.txt
