In [1]:
import numpy as np

In [4]:
def convolve(x, kernel):
    x_height = x.shape[0]
    x_width = x.shape[1]
    
    kernel_height = kernel.shape[0]
    kernel_width = kernel.shape[1]
    
    H = (kernel_height - 1) // 2
    W = (kernel_width - 1) // 2
    
    out = np.zeros((x_height, x_width))
    # iterate over all the pixel of image X
    for i in np.arange(H, x_height - H):
        for j in np.arange(W, x_width - W):
            sum = 0
            # iterate over the filter
            for k in np.arange(-H, H + 1):
                for l in np.arange(-W, W + 1):
                    # get the corresponding value from image and filter
                    a = x[i + k, j + l]
                    w = kernel[H + k, W + l]
                    sum += (w * a)
            out[i, j] = sum
    return out

In [5]:
# Define the 3x3 kernel
x_kernel = np.array([[-1, 0, 1],
                     [-1, 0, 1],
                     [-1, 0, 1]])

In [35]:
x = np.random.randint(0, 256, (5, 5), dtype=np.uint8)
print("Input Matrix (5x5):")
print(x)

Input Matrix (5x5):
[[ 65  63 227  76 135]
 [146  99 179   3 191]
 [ 83 150 223 143 230]
 [248  47 153  41 253]
 [ 30 248 114 163 218]]


In [36]:
output = convolve(x, x_kernel)
print("\nOutput Matrix after Convolution:")
print(output)


Output Matrix after Convolution:
[[   0.    0.    0.    0.    0.]
 [   0.  335.  -90.  -73.    0.]
 [   0.   78. -109.  119.    0.]
 [   0.  129.  -98.  211.    0.]
 [   0.    0.    0.    0.    0.]]
